<color[white,green]>
	<button[5,5,7,4,local://test/]>
		what?
		<color[blue]>
			test!
		</color>
	</button>
</color>
<color[white,blue]>
	<button[20,5,local://test/]>
		test!
	</button>
</color>
<color[white,red]>
	hey!
</color>
