<clear[white]>
<color[white,green]>
	<button[5,2,7,4,local://test/]>
		what?
		<color[blue]>
			test.
		</color>
	</button>
</color>
<color[white,blue]>
	<button[20,2,local://test/]>
		boo!
	</button>
</color>
